### ISSUE TITLE
Misleading message when sending/saving with no recipients

### ISSUE THREAD

**Issue by mackensen** [CLAMP-IT/clampmail#31]
If you try to send or save a draft with no recipients you receive the message "There are no users you are capable of emailing." I suspect most users grok right away what the actual problem is, but it would be nice to provide a better notice.

**Comment by jlmoreau** [comment]
Agreed with @mackensen . For us the problem is the notice displays in green (at least in Boost) which gives rushed users enough confidence to believe they actually sent the message. It might be better if this would raise an error similarly to how leaving out Subject does as a required field (which users also do and sometimes fail to notice).
